### ISSUE TITLE
Check tex manuscript

### ISSUE THREAD

**Issue by titipata** [titipata/science_concierge_tex#2]
@daniel-acuna and @bluenex, can you guys check the manuscript compared to current [.docx file](https://github.com/titipata/science_concierge/tree/master/article)

**Comment by bluenex** [comment]
roger

**Comment by titipata** [comment]
Can you change the following (below). I will update once I see typos. We can put final `pdf` file when we finish.
- `q` in manuscript line 109 to `$q$`
- `t-SNE` to `$t$-SNE`
